mysql:
  dns: "root:123456@tcp(127.0.0.1:3306)/go_chat?charset=utf8mb4&parseTime=True&loc=Local"
app:
  salt: "go_chat"  #密码加盐
  ip: "127.0.0.1"
  http_server_port: "9090"       # http 端口
  websocket_server_port: "9091"  # websocket 端口
  rpc-port: "9092"  # rpc 端口
  worker_pool_size: 10  # 业务 worker 队列数量
  max_worker_task: 1024 #队列中，每个 worker 的最大任务存储数量
jwt:
  sign_key: "go_lwf"
  expire_time: 720  # hour

#https://pkg.go.dev/github.com/go-redis/redis/v8#section-readme
redis:
  addr: "127.0.0.1:6379"
  password: "123456" #no password set
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"